language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

env:
  global:
    - APP_ENV=testing
    - DOCTRINE_HOST=127.0.0.1
    - DOCTRINE_USER=root
    - DOCTRINE_PASSWORD=
    - DOCTRINE_DATABASE=ci_tests

before_script:
  - composer self-update
  - composer install --optimize-autoloader
  - mysql -e 'create database ci_tests;'
  - cd ./tests/Bootstrap/ && ../../vendor/bin/doctrine orm:schema-tool:create && cd ../../

script:
  - ./vendor/bin/phpunit ./tests
  - ./vendor/bin/phpcs ./src/ --standard=PSR2