language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - APP_ENV=testing

before_script:
  - composer self-update
  - composer install --optimize-autoloader

script:
  - ./vendor/bin/phpunit ./tests
  - ./vendor/bin/phpcs ./src/ --standard=PSR2